trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureContainerApps@1
  inputs:
    appSourcePath: './'
    azureSubscription: '380a10c2-0513-492d-ac62-b291196fe623'
    acrName: 'containersofthestorm'
    containerAppName: 'stormapp'
    resourceGroup: 'CCStormhorn'
